### ISSUE TITLE
Attachments are shown at a test class level

### ISSUE THREAD

**Issue by MJB222398** [jenkinsci/junit-attachments-plugin#156]
### Jenkins and plugins versions report

Jenkins 2.492.1

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows and Ubuntu

### Reproduction steps

Using this example TestResults.xml file:

``` xml
<testsuites>
	<testsuite name="MyTestAssembly.dll" tests="3" skipped="0" failures="0" errors="0" time="0.0039629999999999995" timestamp="2025-03-11T15:09:45" hostname="jenkins-worker5" id="0" package="MyTestAssembly.dll">
		<properties/>
		<testcase classname="MyTestAssembly.Tests.JUnit.JunitPluginTests" name="TestCase1" time="0.0033490">
			<system-out><![CDATA[I am TestCase1

[[ATTACHMENT|C:\Users\MyUser\source\repos\junit-attachments-plugin\work\workspace\attachments-fixes\TestCase1\Attachment.txt]]
]]></system-out>
		</testcase>
		<testcase classname="MyTestAssembly.Tests.JUnit.JunitPluginTests" name="TestCase2" time="0.0004200">
			<system-out><![CDATA[I am TestCase2

[[ATTACHMENT|C:\Users\MyUser\source\repos\junit-attachments-plugin\work\workspace\attachments-fixes\TestCase2\Attachment.txt]]
]]></system-out>
		</testcase>
		<testcase classname="MyTestAssembly.Tests.JUnit.JunitPluginTests" name="TestCase3" time="0.0001940">
			<system-out><![CDATA[I am TestCase3

[[ATTACHMENT|C:\Users\MyUser\source\repos\junit-attachments-plugin\work\workspace\attachments-fixes\TestCase3\Attachment.txt]]
]]></system-out>
		</testcase>
		<system-out/>
		<system-err/>
	</testsuite>
</testsuites>
```

Process the test results:

``` groovy
junit(
	testResults: "TestResults.xml",
	stdioRetention: "all",
	testDataPublishers: [[$class:'AttachmentPublisher']],
	skipPublishingChecks: true)
```

This results in the attachments being displayed at the test class level as well as the level of the individual test cases.

The attachments belong to test methods (testcase name property in XML) so in my opinion it doesn't make sense to render them at the test class level. This is made even worse by the fact that the attachment name is (pefectly legitimately I might add) the same for each test case (Attachment.txt). At the test class level it then of course sees them as duplicates and only renders the one (and you have no idea which test case it came from). 

Furthermore, if you drill down into each of the three test cases above you will see that the while each is getting the attachment shown for it, it is the attachment for the first test case that is repeated for all three rather than showing the correct attachment for each test case. This of course is a major issue, a user could be trying to diagnose a test failure by looking at the attachment without realizing its actually the attachment from another test case.

### Expected Results

I would expect that attachments are not shown at the test class level at all. I do not see a use for this. Maybe someone could give a reason otherwise?

I would also expect that the correct attachments are shown for each test case.

### Actual Results

Attachments are shown at a test class level and test cases have the incorrect attachments shown for them.

### Are you interested in contributing a fix?

I might be yes, if we can agree on what to do?

**Comment by jonesbusy** [comment]
I think attachment at the class level must be kept. Removing is no only a breaking change but is useful when having large suite where attachment have a random or just unique name. No need to navigate on every test.

The issue you mention must be fixed if cause issue with same attachment name. Perhaps group them on different section of the table? Add a prefix? 

But remove them is not a solution in my opinion 🤔

**Comment by MJB222398** [comment]
Yes ok if some people need them at class level we can keep them there. But imagine you have 10 test cases in a test class and each produces 10 attachments. You will see 100 attachments at the class level, it would be quite a mess. So maybe we make it configurable? Is it possible to pass options to the attachments plugin? If so we can add a showAttachmentsAtClassLevel option that defaults to true?

**Comment by jonesbusy** [comment]
Configurable to hide can be an option. And keep them visible by default. It should be possible to add a databound setter on https://github.com/jenkinsci/junit-attachments-plugin/blob/main/src/main/java/hudson/plugins/junitattachments/AttachmentPublisher.java#L31

**Comment by MJB222398** [comment]
@jonesbusy Please bear with me, not a Jenkins plugin developer, nor even a Java one. I think  what you are suggesting is:

```java
    private boolean showAttachmentsAtClassLevel = true;

    @DataBoundConstructor
    public AttachmentPublisher() {
    }

    public boolean getShowAttachmentsAtClassLevel() {
        return showAttachmentsAtClassLevel;
    }

    @DataBoundSetter
    public void setShowAttachmentsAtClassLevel(boolean showAttachmentsAtClassLevel) {
        this.showAttachmentsAtClassLevel = showAttachmentsAtClassLevel;
    }
```

But from what I can see I need this class to implement SimpleBuildStep or similar in order to wire this all up? Please do correct me if I am wrong. Would appreciate any support/pointing in the right direction in making this change,

**Comment by jonesbusy** [comment]
Yes something like this. You might also allow null value and set the value to true when null on the readResolve when the object is read from disk

https://www.jenkins.io/doc/developer/persistence/backward-compatibility/

**Comment by MJB222398** [comment]
OK I have added a PR (#157) for the new option to show/hide attachments at a class level. I can address the other issues here in separate PRs.

**Comment by jonesbusy** [comment]
Fixed by https://github.com/jenkinsci/junit-attachments-plugin/pull/157

**Comment by MJB222398** [comment]
Not quite fixed yet, This bit still outstanding:

_Furthermore, if you drill down into each of the three test cases above you will see that the while each is getting the attachment shown for it, it is the attachment for the first test case that is repeated for all three rather than showing the correct attachment for each test case. This of course is a major issue, a user could be trying to diagnose a test failure by looking at the attachment without realizing its actually the attachment from another test case._

Will submit a PR for that too
